Repository redpanda-data/helm-charts, pull requests merged in 2022-12, with the labels that each got.

#188 #187 Check `Capabilities` to render `PodDisruptionBudget` manifest
  charts/redpanda/Chart.yaml
  charts/redpanda/templates/poddisruptionbudget.yaml
  charts/redpanda/values.yaml
Labels: blocked

#219 redpanda: add rack awareness feature
  .github/annotate_kind_nodes.sh
  .github/workflows/pull_requests.yaml
  charts/redpanda/Chart.yaml
  charts/redpanda/README.md
  charts/redpanda/ci/06-rack-awareness.yaml
  charts/redpanda/templates/configmap.yaml
  charts/redpanda/templates/rbac.yaml
  charts/redpanda/templates/statefulset.yaml
  charts/redpanda/templates/tests/test-rack-awareness.yaml
  charts/redpanda/values.schema.json
  charts/redpanda/values.yaml
Labels: enhancement

#228 Update README.md
  charts/redpanda/Chart.yaml
  charts/redpanda/README.md
Labels: documentation
