Repository redpanda-data/helm-charts, pull requests merged in 2023-03, with the labels that each got.

#320 Add LoadBalancer service
  charts/redpanda/Chart.yaml
  charts/redpanda/templates/NOTES.txt
  charts/redpanda/templates/_helpers.tpl
  charts/redpanda/templates/service.loadbalancer.yaml
  charts/redpanda/values.schema.json
  charts/redpanda/values.yaml
Labels: enhancement

#375 chore: allow resource configuration of initContainers
  charts/redpanda/Chart.yaml
  charts/redpanda/ci/09-initcontainers-resources-values.yaml
  charts/redpanda/templates/statefulset.yaml
  charts/redpanda/values.schema.json
  charts/redpanda/values.yaml
Labels: bug, chart:redpanda

#380 chore: remove chown initContainer
  charts/redpanda/Chart.yaml
  charts/redpanda/templates/_helpers.tpl
  charts/redpanda/templates/statefulset.yaml
  charts/redpanda/values.schema.json
  charts/redpanda/values.yaml
Labels: enhancement, chart:redpanda

#383 Update appVersion from v22.3.13 to v23.1.1
  .github/workflows/pull_requests.yaml
  charts/redpanda/Chart.yaml
Labels: chart:redpanda

#401 set up test matrix to provider better test coverage in less time
  .github/workflows/pull_requests.yaml
Labels: tests

#404 fix: fixing broken links
  README.md
Labels: documentation, enhancement

#402 Remove examples folder
  contrib/README.md
  contrib/datadog-annotations/README.md
  examples/README.md
  examples/with-external-via-nodeport/README.md
  examples/with-sasl/README.md
  examples/with-selfsigned-tls/README.md
Labels: documentation

#391 chore: add task file for common operations
  Taskfile.yaml
  scripts/change-default-sc.sh
Labels: enhancement

#406 feat: enable setting ownership via initContainer
  charts/redpanda/Chart.yaml
  charts/redpanda/templates/statefulset.yaml
  charts/redpanda/values.schema.json
  charts/redpanda/values.yaml
Labels: enhancement, chart:redpanda
