Repository redpanda-data/helm-charts, pull requests merged in 2023-01, with the labels that each got.

#257 Allow adding `extraEnv` and `extraEnvFrom` to post upgrade job
  charts/redpanda/Chart.yaml
  charts/redpanda/templates/_tplvalues.tpl
  charts/redpanda/templates/post-upgrade.yaml
  charts/redpanda/values.schema.json
  charts/redpanda/values.yaml
Labels: enhancement

#266 redpanda: add missed example command to tests, and fix command
  charts/redpanda/Chart.yaml
  charts/redpanda/templates/_example-commands.tpl
  charts/redpanda/templates/tests/test-kafka-sasl-status.yaml
Labels: bug

#268 feat: add preStart and postStop scripts
  charts/redpanda/Chart.yaml
  charts/redpanda/templates/_helpers.tpl
  charts/redpanda/templates/secret.yaml
  charts/redpanda/templates/statefulset.yaml
  charts/redpanda/values.yaml
Labels: enhancement, P0

#274 console: upgrade appVersion from v2.0.2 to v2.1.1
  charts/console/Chart.yaml
Labels: chart:console

#297 redpanda: default to putting redpanda on separate nodes
  charts/redpanda/Chart.yaml
  charts/redpanda/values.yaml
Labels: chart:redpanda

#288 feat: enable upgrade tests on ct.
  .github/ct.yaml
  .github/workflows/pull_requests.yaml
Labels: blocked

#304 redpanda: fix lifecycle hooks
  charts/redpanda/Chart.yaml
  charts/redpanda/templates/_helpers.tpl
  charts/redpanda/templates/secret.yaml
Labels: chart:redpanda

#277 console: set service targetPort to config listenPort
  charts/console/Chart.yaml
  charts/console/templates/service.yaml
Labels: bug

#292 redpanda: allow super small memory settings for development
  charts/redpanda/Chart.yaml
  charts/redpanda/templates/NOTES.txt
  charts/redpanda/templates/_helpers.tpl
Labels: chart:redpanda
